name: Auto Deploy Agents to Cloud Run

on:
  push:
    paths:
      - 'student/orch*/agents/agent*/**'

jobs:
  deploy-agents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: proj-459908

    - name: Find changed agents
      id: find-agents
      run: |
        echo "🔍 Detecting changes..."
        git fetch --unshallow || true

        BEFORE_SHA="${{ github.event.before }}"
        AFTER_SHA="${{ github.sha }}"

        # Validate BEFORE_SHA
        if ! git cat-file -e "$BEFORE_SHA"^{commit} 2>/dev/null; then
          echo "⚠️ BEFORE_SHA is invalid, falling back to HEAD~1"
          BEFORE_SHA=$(git rev-parse HEAD~1)
        fi

        echo "Comparing $BEFORE_SHA to $AFTER_SHA"
        CHANGED_AGENTS=$(git diff --name-only "$BEFORE_SHA" "$AFTER_SHA" \
          | grep '^student/orch.*/agents/agent[^/]*' \
          | cut -d/ -f1-5 \
          | sort -u)

        echo "CHANGED_AGENTS<<EOF" >> $GITHUB_ENV
        echo "$CHANGED_AGENTS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Deploy changed agents to Cloud Run
      run: |
        echo "🚀 Agents to deploy: $CHANGED_AGENTS"
        if [ -z "$CHANGED_AGENTS" ]; then
          echo "✅ No changed agents to deploy."
          exit 0
        fi

        echo "$CHANGED_AGENTS" | while read agent_path; do
          [ -z "$agent_path" ] && continue
          agent_name=$(basename "$agent_path")
          echo "🔧 Deploying $agent_name from $agent_path"

          gcloud builds submit "$agent_path" \
            --tag gcr.io/proj-459908/$agent_name

          gcloud run deploy $agent_name \
            --image gcr.io/proj-459908/$agent_name \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
        done
